server:
  port: 8080
spring:
  application:
    name: "appFranquicias"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include:
adapters:
  r2dbc:
    host: "${POSTGRES_HOST}"
    port: "${POSTGRES_PORT}"
    database: "${POSTGRES_DB}"
    schema: "${POSTGRES_SCHEMA}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
